@baseUrl = http://localhost:3333

# @name create_account
POST {{baseUrl}}/users
Content-Type: application/json

{
  "name": "Eduardo4",
  "email": "edu4@test.com",
  "password": "123"
}

###

# @name create_product
POST {{baseUrl}}/products
Content-Type: application/json

{
  "name": "massa com frango",
  "ingredients": ["frango", "massa"],
  "category": "PF",
  "price": 50,
  "description": "Massa fresca com frango",
  "image": "teste"
}

###

# @name get_all_products
GET {{baseUrl}}/products?searchTerms=massa
Content-Type: application/xhtml+xml

###

# @name delete_product
DELETE {{baseUrl}}/products/8
Content-Type: application/xhtml+xml

###

# @name get_all_categories
GET {{baseUrl}}/categories
Content-Type: application/xhtml+xml