@baseUrl = http://localhost:3333

# @name create_account
POST {{baseUrl}}/users
Content-Type: application/json

{
  "name": "Eduardo",
  "email": "edu1@test.com",
  "password": "123",
  "isAdmin": true
}

###

# @name create_session
POST {{baseUrl}}/sessions
Content-Type: application/json

{
  "email": "edu1@test.com",
  "password": "123"
}

###

# @name create_product
POST {{baseUrl}}/products
Content-Type: application/json

{
  "name": "Strogonoff",
  "ingredients": ["Arroz", "Frango", "Tomate"],
  "category": "Refeição",
  "price": 40,
  "description": "Strogonoff de frango com molho",
  "image": "teste"
}

###

# @name update_product
PUT {{baseUrl}}/products/1
Content-Type: application/json

{
  "name": "massa parmegiana",
  "ingredients": ["tomate", "massa", "alho"],
  "category": "Refeições",
  "price": 30,
  "description": "Massa fresca com alho e tomate",
  "image": "teste 1"
}

###

# @name get_all_products
GET {{baseUrl}}/products
Content-Type: application/xhtml+xml

###

# @name get_products
GET {{baseUrl}}/products?searchTerms=Arroz
Content-Type: application/xhtml+xml

###

# @name delete_product
DELETE {{baseUrl}}/products/8
Content-Type: application/xhtml+xml

###

# @name show_product
GET {{baseUrl}}/products/10
Content-Type: application/xhtml+xml

###

# @name get_all_categories
GET {{baseUrl}}/categories
Content-Type: application/xhtml+xml

###

# @name show_ingredients
GET {{baseUrl}}/ingredients/3
Content-Type: application/xhtml+xml

