@baseUrl = http://localhost:3333

# @name create_account
POST {{baseUrl}}/users
Content-Type: application/json

{
  "name": "Eduardo4",
  "email": "edu4@test.com",
  "password": "123"
}

###

# @name create_product
POST {{baseUrl}}/products
Content-Type: application/json

{
  "name": "tomate com frango",
  "category": "PF",
  "price": 50,
  "description": "Tomates frescos",
  "image": "teste"
}

###

# @name get_products
GET {{baseUrl}}/products
Content-Type: application/xhtml+xml
